# Generated by Django 5.1.3 on 2024-11-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbexample', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
